"""add firstname and lastname to users

Revision ID: 19f0af9fbb9a
Revises: 001
Create Date: 2026-02-15 22:46:10.129866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f0af9fbb9a'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('game1_score', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('game2_score', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('game3_score', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('game4_score', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('game5_score', sa.Float(), nullable=True))
    op.add_column('scores', sa.Column('total_score', sa.Float(), nullable=True))
    op.drop_column('scores', 'subject')
    op.drop_column('scores', 'score')
    op.add_column('users', sa.Column('firstname', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('region', sa.String(length=128), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('users', 'region')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.add_column('scores', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('scores', sa.Column('subject', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('scores', 'total_score')
    op.drop_column('scores', 'game5_score')
    op.drop_column('scores', 'game4_score')
    op.drop_column('scores', 'game3_score')
    op.drop_column('scores', 'game2_score')
    op.drop_column('scores', 'game1_score')
    # ### end Alembic commands ###
