"""change_score_to_1_to_1_relationship

Revision ID: cc9a6305c973
Revises: 19f0af9fbb9a
Create Date: 2026-02-24 00:22:00.366570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9a6305c973'
down_revision: Union[str, None] = '19f0af9fbb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Create new table with correct structure
    op.create_table('scores_new',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('game1_score', sa.Float(), nullable=False, default=0),
        sa.Column('game2_score', sa.Float(), nullable=False, default=0),
        sa.Column('game3_score', sa.Float(), nullable=False, default=0),
        sa.Column('game4_score', sa.Float(), nullable=False, default=0),
        sa.Column('game5_score', sa.Float(), nullable=False, default=0),
        sa.Column('total_score', sa.Float(), nullable=False, default=0),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_scores_new_user_id'), 'scores_new', ['user_id'], unique=True)
    
    # Step 2: Migrate existing data
    # For users who already have scores, copy the latest score
    op.execute("""
        INSERT INTO scores_new (user_id, game1_score, game2_score, game3_score, game4_score, game5_score, total_score, created_at)
        SELECT DISTINCT ON (s.user_id) 
            s.user_id,
            COALESCE(s.game1_score, 0),
            COALESCE(s.game2_score, 0),
            COALESCE(s.game3_score, 0),
            COALESCE(s.game4_score, 0),
            COALESCE(s.game5_score, 0),
            COALESCE(s.total_score, 0),
            s.created_at
        FROM scores s
        ORDER BY s.user_id, s.created_at DESC
    """)
    
    # Step 3: For users without scores, create default entries
    op.execute("""
        INSERT INTO scores_new (user_id, game1_score, game2_score, game3_score, game4_score, game5_score, total_score)
        SELECT u.id, 0, 0, 0, 0, 0, 0
        FROM users u
        WHERE u.id NOT IN (SELECT user_id FROM scores_new)
    """)
    
    # Step 4: Drop old table and rename new one
    op.drop_table('scores')
    op.rename_table('scores_new', 'scores')
    op.create_index(op.f('ix_scores_user_id'), 'scores', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create old table structure
    op.create_table('scores_old',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('game1_score', sa.Float(), nullable=True),
        sa.Column('game2_score', sa.Float(), nullable=True),
        sa.Column('game3_score', sa.Float(), nullable=True),
        sa.Column('game4_score', sa.Float(), nullable=True),
        sa.Column('game5_score', sa.Float(), nullable=True),
        sa.Column('total_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_old_id'), 'scores_old', ['id'], unique=False)
    op.create_index(op.f('ix_scores_old_user_id'), 'scores_old', ['user_id'], unique=False)
    
    # Step 2: Copy data back
    op.execute("""
        INSERT INTO scores_old (user_id, game1_score, game2_score, game3_score, game4_score, game5_score, total_score, created_at)
        SELECT user_id, game1_score, game2_score, game3_score, game4_score, game5_score, total_score, created_at
        FROM scores
    """)
    
    # Step 3: Drop new table and rename old one
    op.drop_table('scores')
    op.rename_table('scores_old', 'scores')
    # ### end Alembic commands ###
